=head1 NAME

CRC32 - Perl interface cyclic redundency check generation

=head1 SYNOPSIS

    use String::CRC32;
    
    $crc = crc32("some string");

=head1 DESCRIPTION

The B<CRC32> module calculates CRC of 32 bit lenghts. 
It generates the same CRC values as ZMODEM, PKZIP, PICCHECK and
many others.

=head1 AUTHOR

Soenke J. Peters <peters@simprovement.com>

=head1 COPYRIGHT

CRC algorithm code taken from CRC-32 by Craig Bruce. 
The module stuff is inspired by a similar perl module called 
String::CRC by David Sharnoff & Matthew Dillon.

The author of this package disclaims all copyrights and 
releases it into the public domain.

